swagger:
  specs:
    default:
      pathJson: "openapi.json"
      pathYaml: "openapi.yaml"
      overrideSpec: "classpath:header.yml"
      resourcePackages:
        - io.bootique.swagger.openapi3.demo

swaggerui:
  default:
    specPath: openapi.json