# Provides default configuration that is merged with endpoints metadata into the app's OpenAPI model.
# You can add anything that OpenAPI 3.0.x specification supports one level below "openAPI:" key,
# e.g. "servers", "paths", etc. See https://swagger.io/docs/specification/basic-structure/ for more details.
openAPI:
  info:
    version: '1.0'
    title: "Bootique OpenAPI 3.0 Demo"
    description: "Demonstrates OpenAPI v3 API spec generation and presentation"
    contact:
      email: root@example.org
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
